package Service;

public class MainService {
    //TODO DE IMPLEMENTAT 2 COLECTII SORTATE (POATE PT PROPRIETATI LUATE DIN BD) - IDEE

    //IN LOC DE CALENDARPROPRIETATE FAC O CLASA VIZUALIZARE (id_proprietate, datetimenow)
    //DE FIECARE DATA CAND INTRU PE O PROPRIETATE SALVEZ VIZUALIZARA INTR O LISTA

    //FOLOSESC TREESET PT A STOCA PROPRIETATILE SI PT A LE SORTA
}
